config/routes.rb
Rails.application.routes.draw do
  resources :documento_alunos
  resources :tipo_documentos
  resources :projeto_alunos
  resources :projeto_professors
  resources :tipo_bolsas
  resources :alunos
  resources :cotas
  resources :projetos
  resources :area_conhecimentos
  resources :professors
  resources :cursos
  resources :instituicaos
  resources :laboratorios
  resources :centros
  resources :tipo_professors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "application#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :curso
  belongs_to :cota

  has_many :documento_alunos
  accepts_nested_attributes_for :documento_alunos, reject_if: :all_blank, allow_destroy: true

  has_many :projeto_alunos
  has_many :projetos, through: :projeto_alunos
  accepts_nested_attributes_for :projetos


end

app/models/area_conhecimento.rb
class AreaConhecimento < ApplicationRecord
end

app/models/centro.rb
class Centro < ApplicationRecord
  validates  :nome, :sigla, :presence => { :message => " é um campo obrigatório !"}
end

app/models/cota.rb
class Cota < ApplicationRecord
  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
end

app/models/curso.rb
class Curso < ApplicationRecord
  belongs_to :centro
  belongs_to :instituicao

  validates  :nome, :sigla, :presence => { :message => " é um campo obrigatório !"}
end

app/models/documento_aluno.rb
class DocumentoAluno < ApplicationRecord
  belongs_to :aluno
  belongs_to :tipo_documento

  has_one_attached :documento
end

app/models/instituicao.rb
class Instituicao < ApplicationRecord
  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
end

app/models/laboratorio.rb
class Laboratorio < ApplicationRecord
  belongs_to :centro

  #validates_associated :centro, :message => " O centro deve existir !"

  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
  validates  :sigla, :presence => { :message => " é um campo obrigatório !"}
  validates  :centro, :presence => { :message => " é um campo obrigatório !"}
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :tipo_professor
  belongs_to :laboratorio

  has_many :projeto_professors
  has_many :projetos, through: :projeto_professors
  accepts_nested_attributes_for :projetos
end

app/models/projeto.rb
class Projeto < ApplicationRecord
  belongs_to :area_conhecimento

  has_many :projeto_professors
  has_many :projeto_alunos

  accepts_nested_attributes_for :projeto_alunos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :projeto_professors, reject_if: :all_blank, allow_destroy: true

  has_many :alunos, through: :projeto_alunos
  accepts_nested_attributes_for :alunos

  has_many :professors, through: :projeto_professors
  accepts_nested_attributes_for :professors
end

app/models/projeto_aluno.rb
class ProjetoAluno < ApplicationRecord
  belongs_to :projeto
  belongs_to :aluno
  belongs_to :tipo_bolsa
end

app/models/projeto_professor.rb
class ProjetoProfessor < ApplicationRecord
  belongs_to :projeto
  belongs_to :professor

  
end

app/models/tipo_bolsa.rb
class TipoBolsa < ApplicationRecord

  validates  :nome, :valor, :presence => { :message => " é um campo obrigatório !"}

end

app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord
end

app/models/tipo_professor.rb
class TipoProfessor < ApplicationRecord

  validates  :descricao, :presence => { :message => "é um campo obrigatório !"}

end

app/controllers/projeto_alunos_controller.rb
class ProjetoAlunosController < ApplicationController
  before_action :set_projeto_aluno, only: %i[ show edit update destroy ]

  # GET /projeto_alunos or /projeto_alunos.json
  def index
    @projeto_alunos = ProjetoAluno.all
  end

  # GET /projeto_alunos/1 or /projeto_alunos/1.json
  def show
  end

  # GET /projeto_alunos/new
  def new
    @projeto_aluno = ProjetoAluno.new
  end

  # GET /projeto_alunos/1/edit
  def edit
  end

  # POST /projeto_alunos or /projeto_alunos.json
  def create
    @projeto_aluno = ProjetoAluno.new(projeto_aluno_params)

    respond_to do |format|
      if @projeto_aluno.save
        format.html { redirect_to @projeto_aluno, notice: "Projeto aluno was successfully created." }
        format.json { render :show, status: :created, location: @projeto_aluno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @projeto_aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projeto_alunos/1 or /projeto_alunos/1.json
  def update
    respond_to do |format|
      if @projeto_aluno.update(projeto_aluno_params)
        format.html { redirect_to @projeto_aluno, notice: "Projeto aluno was successfully updated." }
        format.json { render :show, status: :ok, location: @projeto_aluno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @projeto_aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projeto_alunos/1 or /projeto_alunos/1.json
  def destroy
    @projeto_aluno.destroy!

    respond_to do |format|
      format.html { redirect_to projeto_alunos_path, status: :see_other, notice: "Projeto aluno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto_aluno
      @projeto_aluno = ProjetoAluno.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def projeto_aluno_params
      params.expect(projeto_aluno: [ :projeto_id, :aluno_id, :inicio, :fim, :plano_trabalho, :tipo_bolsa_id ])
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/helpers/cotas_helper.rb
module CotasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/projeto_alunos_helper.rb
module ProjetoAlunosHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/projeto_alunos/_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">

  <div>
    <%= f.label :projeto_id, style: "display: block" %>
    <%= f.text_field :projeto_id %>
  </div>

  <div>
    <%= f.label :aluno_id, style: "display: block" %>
    <%= f.text_field :aluno_id %>
  </div>

  <div>
    <%= f.label :inicio, style: "display: block" %>
    <%= f.date_field :inicio %>
  </div>

  <div>
    <%= f.label :fim, style: "display: block" %>
    <%= f.date_field :fim %>
  </div>

  <div>
    <%= f.label :plano_trabalho, style: "display: block" %>
    <%= f.text_field :plano_trabalho %>
  </div>

  <div>
    <%= f.label :tipo_bolsa_id, style: "display: block" %>
    <%= f.text_field :tipo_bolsa_id %>
  </div>

  <button type="button" data-action="nested-form#remove">Remove task</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/projeto_alunos/_projeto_aluno.html.erb
<div id="<%= dom_id projeto_aluno %>">
  <p>
    <strong>Projeto:</strong>
    <%= projeto_aluno.projeto_id %>
  </p>

  <p>
    <strong>Aluno:</strong>
    <%= projeto_aluno.aluno_id %>
  </p>

  <p>
    <strong>Inicio:</strong>
    <%= projeto_aluno.inicio %>
  </p>

  <p>
    <strong>Fim:</strong>
    <%= projeto_aluno.fim %>
  </p>

  <p>
    <strong>Plano trabalho:</strong>
    <%= projeto_aluno.plano_trabalho %>
  </p>

  <p>
    <strong>Tipo bolsa:</strong>
    <%= projeto_aluno.tipo_bolsa_id %>
  </p>

</div>

app/views/projeto_alunos/edit.html.erb
<% content_for :title, "Editing projeto aluno" %>

<h1>Editing projeto aluno</h1>

<%= render "form", projeto_aluno: @projeto_aluno %>

<br>

<div>
  <%= link_to "Show this projeto aluno", @projeto_aluno %> |
  <%= link_to "Back to projeto alunos", projeto_alunos_path %>
</div>

app/views/projeto_alunos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projeto alunos" %>

<h1>Projeto alunos</h1>

<div id="projeto_alunos">
  <% @projeto_alunos.each do |projeto_aluno| %>
    <%= render projeto_aluno %>
    <p>
      <%= link_to "Show this projeto aluno", projeto_aluno %>
    </p>
  <% end %>
</div>

<%= link_to "New projeto aluno", new_projeto_aluno_path %>

app/views/projeto_alunos/new.html.erb
<% content_for :title, "New projeto aluno" %>

<h1>New projeto aluno</h1>

<%= render "form", projeto_aluno: @projeto_aluno %>

<br>

<div>
  <%= link_to "Back to projeto alunos", projeto_alunos_path %>
</div>

app/views/projeto_alunos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @projeto_aluno %>

<div>
  <%= link_to "Edit this projeto aluno", edit_projeto_aluno_path(@projeto_aluno) %> |
  <%= link_to "Back to projeto alunos", projeto_alunos_path %>

  <%= button_to "Destroy this projeto aluno", @projeto_aluno, method: :delete %>
</div>