config/routes.rb
Rails.application.routes.draw do
  resources :documento_alunos
  resources :tipo_documentos
  resources :projeto_alunos
  resources :projeto_professors
  resources :tipo_bolsas
  resources :alunos
  resources :cotas
  resources :projetos
  resources :area_conhecimentos
  resources :professors
  resources :cursos
  resources :instituicaos
  resources :laboratorios
  resources :centros
  resources :tipo_professors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "application#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :curso
  belongs_to :cota

  has_many :documento_alunos
  accepts_nested_attributes_for :documento_alunos, reject_if: :all_blank, allow_destroy: true

  has_many :projeto_alunos
  has_many :projetos, through: :projeto_alunos
  accepts_nested_attributes_for :projetos


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area_conhecimento.rb
class AreaConhecimento < ApplicationRecord
end

app/models/centro.rb
class Centro < ApplicationRecord
  validates  :nome, :sigla, :presence => { :message => " é um campo obrigatório !"}
end

app/models/cota.rb
class Cota < ApplicationRecord
  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
end

app/models/curso.rb
class Curso < ApplicationRecord
  belongs_to :centro
  belongs_to :instituicao

  validates  :nome, :sigla, :presence => { :message => " é um campo obrigatório !"}
end

app/models/documento_aluno.rb
class DocumentoAluno < ApplicationRecord
  belongs_to :aluno
  belongs_to :tipo_documento

  has_one_attached :documento
end

app/models/instituicao.rb
class Instituicao < ApplicationRecord
  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
end

app/models/laboratorio.rb
class Laboratorio < ApplicationRecord
  belongs_to :centro

  #validates_associated :centro, :message => " O centro deve existir !"

  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
  validates  :sigla, :presence => { :message => " é um campo obrigatório !"}
  validates  :centro, :presence => { :message => " é um campo obrigatório !"}
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :tipo_professor
  belongs_to :laboratorio

  has_many :projeto_professors
  has_many :projetos, through: :projeto_professors
  accepts_nested_attributes_for :projetos
end

app/models/projeto.rb
class Projeto < ApplicationRecord
  belongs_to :area_conhecimento

  has_many :projeto_professors
  has_many :projeto_alunos

  accepts_nested_attributes_for :projeto_alunos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :projeto_professors, reject_if: :all_blank, allow_destroy: true

  has_many :alunos, through: :projeto_alunos
  accepts_nested_attributes_for :alunos

  has_many :professors, through: :projeto_professors
  accepts_nested_attributes_for :professors
end

app/models/projeto_aluno.rb
class ProjetoAluno < ApplicationRecord
  belongs_to :projeto
  belongs_to :aluno
  belongs_to :tipo_bolsa
end

app/models/projeto_professor.rb
class ProjetoProfessor < ApplicationRecord
  belongs_to :projeto
  belongs_to :professor

  
end

app/models/tipo_bolsa.rb
class TipoBolsa < ApplicationRecord

  validates  :nome, :valor, :presence => { :message => " é um campo obrigatório !"}

end

app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord
end

app/models/tipo_professor.rb
class TipoProfessor < ApplicationRecord

  validates  :descricao, :presence => { :message => "é um campo obrigatório !"}

end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: %i[ show edit update destroy ]

  # GET /alunos or /alunos.json
  def index
    if params[:nome]
      @alunos = Aluno.where("lower(unaccent(nome)) like lower(unaccent( ? ))", "%" + params[:nome].to_s + "%").order(:nome).page(params[:page])
    end
  end

  # GET /alunos/1 or /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos or /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: "Aluno was successfully created." }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1 or /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: "Aluno was successfully updated." }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1 or /alunos/1.json
  def destroy
    @aluno.destroy!

    respond_to do |format|
      format.html { redirect_to alunos_path, status: :see_other, notice: "Aluno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def aluno_params
      #params.expect(aluno: [ :matricula, :nome, :cpf, :curso_id, :cota_id ])
      params.require(:aluno).permit(:matricula, :nome, :cpf, :curso_id, :cota_id, documento_alunos_attributes: [:id, :aluno_id, :tipo_documento_id, :documento, :_destroy])
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/helpers/cotas_helper.rb
module CotasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/alunos/_aluno.html.erb
<div id="<%= dom_id aluno %>">
  <p>
    <strong>Matricula:</strong>
    <%= aluno.matricula %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= aluno.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= aluno.cpf %>
  </p>

  <p>
    <strong>Curso:</strong>
    <%= aluno.curso_id %>
  </p>

  <p>
    <strong>Cota:</strong>
    <%= aluno.cota_id %>
  </p>

</div>

app/views/alunos/_doc_form.html.erb
<div class="rails-nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
<div class="row">
  <div class="col-2">
    <div class="form-label">Documento</div>
    <%= f.collection_select :tipo_documento_id, TipoDocumento.order(:nome), :id, :nome, {:include_blank => ""} , {class: "form-select"} %>
  </div>
  <div class="col-8">
    <div class="form-label">Arquivo</div>
    <%= f.file_field :documento,  class: "form-control" %>
  </div>
  <div class="col-2">
    <div class="form-label"></div>
    <button type="button" data-action="rails-nested-form#remove" class="btn btn-dark mt-4">Remove</button>
  </div>

  <%= f.hidden_field :_destroy %>

</div>
</div>

app/views/alunos/_form.html.erb
<%= form_with model: aluno, data: { controller: 'rails-nested-form', rails_nested_form_wrapper_selector_value: '.rails-nested-form-wrapper' } do |form| %>
  <% if aluno.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
        <% aluno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-2">
      <%= form.label :matricula, style: "display: block", class: "form-label" %>
      <%= form.text_field :matricula, class: "form-control col-sm-10" %>
    </div>
    <div class="col-8">
      <%= form.label :nome, style: "display: block" , class: "form-label" %>
      <%= form.text_field :nome, class: "form-control col-sm-10" %>
    </div>
  </div>

  <div class="row">
    <div class="col-4">
      <%= form.label :curso_id, style: "display: block", class: "form-label" %>
      <%= form.collection_select :curso_id, Curso.all.order(:nome), :id, :nome, {:include_blank => ""}, {class: "form-select"} %>
    </div>
    <div class="col-2">
      <%= form.label :cota_id, style: "display: block", class: "form-label" %>
      <%= form.collection_select :cota_id, Cota.all, :id, :nome, {:include_blank => ""}, {class: "form-select"} %>
    </div>
    <div class="col-2">
      <%= form.label :cpf, style: "display: block", class: "form-label" %>
      <%= form.text_field :cpf, class: "form-control col-sm-10" %>
    </div>
  </div>

  </br>

  <div class="card">
    <div class="card-body">
      <div class="card-header">Documentos</div>
      <div class="card-body">
        <template data-rails-nested-form-target="template">
        <%= form.fields_for :documento_alunos, DocumentoAluno.new, child_index: 'NEW_RECORD' do |doc| %>
          <%= render "doc_form", f: doc %>
        <% end %>
        </template>

        <%= form.fields_for :documento_alunos do |doc| %>
          <%= render "doc_form", f: doc %>
        <% end %>

        <div data-rails-nested-form-target="target"></div>
        <button type="button" data-action="rails-nested-form#add" class="btn btn-dark mt-3">Add Doc.</button>

      </div>
    </div>
  </div>



  <div>
    <%= form.submit "Salvar", class: "btn btn-dark mt-3" %>
    <%= link_to "Voltar", alunos_path, class: "btn btn-dark mt-3" %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<% content_for :title, "Editing aluno" %>

<h1>Edit aluno</h1>

<%= render "form", aluno: @aluno %>

app/views/alunos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Alunos</h1>

<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Consultar
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">

        <%= form_with url: alunos_path, method: :get do %>
          <%= label_tag :nome, 'Nome:' , {class: "form-label"} %>
          <%= text_field_tag :nome ,{}, {class: "form-control col-sm-10"} %>
          <%= submit_tag 'Pesquisar', {class: "btn btn-dark mt-3"} %>
        <% end %>

      </div>
    </div>
  </div>
</div>

<br/>

<%= link_to "Novo", new_aluno_path, class: "btn btn-dark mt-3" %>

<br/><br/>

<form>
      <table class="table table-striped table-bordered table-hover mt-4">
        <tbody>
          <% if !@alunos.nil? %>
            <%= paginate @alunos, theme: 'bootstrap-5'%>
            <% @alunos.each do |aluno| %>
              <tr class="align-middle">
                <td class="col-lg-4" ><%= link_to aluno.nome, aluno_path(aluno) %></td>
                <td class="col-sm-1" ><%= link_to "Editar", edit_aluno_path(aluno), class: "btn btn-dark btn-sm" %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
</form>

app/views/alunos/new.html.erb
<% content_for :title, "New aluno" %>

<h1>Aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

app/views/alunos/show.html.erb
<p style="color: green"><%= notice %></p>

<h4>Dados do Aluno</h4>
</br>
<div class="container">
  <div class="row">
    <div class="col-12">
      <strong>Matricula:</strong>
      <%= @aluno.matricula %>
      &nbsp;&nbsp;
      <strong>Nome:</strong>
      <%= @aluno.nome %>
      &nbsp;&nbsp;
      <strong>Cota:</strong>
      <%= @aluno.cota.nome %>
      </br>
      <strong>Curso:</strong>
      <%= @aluno.curso.nome %>

      <br/><br/>

        <% @aluno.projeto_alunos.each do |projeto_aluno| %>
          <div class="card">
            <div class="card-header">Projeto</div>
              <div class="card-body">

                <strong>Titulo:</strong>&nbsp;<%= projeto_aluno.projeto.titulo %> </br>
                <strong>Inicio:</strong>&nbsp;<%= projeto_aluno.projeto.inicio %>&nbsp;&nbsp;&nbsp;
                <strong>Fim:</strong>&nbsp;<%= projeto_aluno.projeto.fim %>

                <div class="card">
                  <div class="card-header">Orientador</div>
                  <div class="card-body">
                    <% projeto_aluno.projeto.projeto_professors.each do |projeto_professor| %>
                      <strong>Orientador:</strong>&nbsp;<%= projeto_professor.professor.nome %>
                    <% end %>
                  </div>
                </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

</br></br></br></br>

<div>
  <%= link_to "Edit this aluno", edit_aluno_path(@aluno) %> |
  <%= link_to "Back to alunos", alunos_path %>

  <%= button_to "Destroy this aluno", @aluno, method: :delete %>
</div>