config/routes.rb
Rails.application.routes.draw do
  resources :documento_alunos
  resources :tipo_documentos
  resources :projeto_alunos
  resources :projeto_professors
  resources :tipo_bolsas
  resources :alunos
  resources :cotas
  resources :projetos
  resources :area_conhecimentos
  resources :professors
  resources :cursos
  resources :instituicaos
  resources :laboratorios
  resources :centros
  resources :tipo_professors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "application#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :curso
  belongs_to :cota

  has_many :documento_alunos
  accepts_nested_attributes_for :documento_alunos, reject_if: :all_blank, allow_destroy: true

  has_many :projeto_alunos
  has_many :projetos, through: :projeto_alunos
  accepts_nested_attributes_for :projetos


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area_conhecimento.rb
class AreaConhecimento < ApplicationRecord
end

app/models/centro.rb
class Centro < ApplicationRecord
  validates  :nome, :sigla, :presence => { :message => " é um campo obrigatório !"}
end

app/models/cota.rb
class Cota < ApplicationRecord
  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
end

app/models/curso.rb
class Curso < ApplicationRecord
  belongs_to :centro
  belongs_to :instituicao

  validates  :nome, :sigla, :presence => { :message => " é um campo obrigatório !"}
end

app/models/documento_aluno.rb
class DocumentoAluno < ApplicationRecord
  belongs_to :aluno
  belongs_to :tipo_documento

  has_one_attached :documento
end

app/models/instituicao.rb
class Instituicao < ApplicationRecord
  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
end

app/models/laboratorio.rb
class Laboratorio < ApplicationRecord
  belongs_to :centro

  #validates_associated :centro, :message => " O centro deve existir !"

  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
  validates  :sigla, :presence => { :message => " é um campo obrigatório !"}
  validates  :centro, :presence => { :message => " é um campo obrigatório !"}
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :tipo_professor
  belongs_to :laboratorio

  has_many :projeto_professors
  has_many :projetos, through: :projeto_professors
  accepts_nested_attributes_for :projetos
end

app/models/projeto.rb
class Projeto < ApplicationRecord
  belongs_to :area_conhecimento

  has_many :projeto_professors
  has_many :projeto_alunos

  accepts_nested_attributes_for :projeto_alunos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :projeto_professors, reject_if: :all_blank, allow_destroy: true

  has_many :alunos, through: :projeto_alunos
  accepts_nested_attributes_for :alunos

  has_many :professors, through: :projeto_professors
  accepts_nested_attributes_for :professors
end

app/models/projeto_aluno.rb
class ProjetoAluno < ApplicationRecord
  belongs_to :projeto
  belongs_to :aluno
  belongs_to :tipo_bolsa
end

app/models/projeto_professor.rb
class ProjetoProfessor < ApplicationRecord
  belongs_to :projeto
  belongs_to :professor

  
end

app/models/tipo_bolsa.rb
class TipoBolsa < ApplicationRecord

  validates  :nome, :valor, :presence => { :message => " é um campo obrigatório !"}

end

app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord
end

app/models/tipo_professor.rb
class TipoProfessor < ApplicationRecord

  validates  :descricao, :presence => { :message => "é um campo obrigatório !"}

end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: %i[ show edit update destroy ]

  # GET /professors or /professors.json
  def index
    if params[:nome]
      @professors = Professor.where("lower(unaccent(nome)) like lower(unaccent( ? ))", "%" + params[:nome].to_s + "%").order(:nome).page(params[:page])
    end
  end

  # GET /professors/1 or /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors or /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: "Professor criado com sucesso." }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1 or /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: "Professor salvo com sucesso." }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1 or /professors/1.json
  def destroy
    @professor.destroy!

    respond_to do |format|
      format.html { redirect_to professors_path, status: :see_other, notice: "Professor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def professor_params
      params.expect(professor: [ :matricula, :nome, :cpf, :tipo_professor_id, :laboratorio_id ])
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/helpers/cotas_helper.rb
module CotasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor) do |form| %>

  <% if professor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
        <% professor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-2">
      <%= form.label :matricula, style: "display: block", class: "form-label" %>
      <%= form.text_field :matricula, class: "form-control col-sm-10" %>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <%= form.label :nome, style: "display: block", class: "form-label" %>
      <%= form.text_field :nome , class: "form-control col-sm-10" %>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <%= form.label :cpf, style: "display: block" , class: "form-label" %>
      <%= form.text_field :cpf, class: "form-control col-sm-10" %>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <%= form.label :tipo_professor_id, style: "display: block", class: "form-label" %>
      <%= form.collection_select :tipo_professor_id, TipoProfessor.all, :id, :descricao, {:include_blank => ""}, {class: "form-select"} %>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <%= form.label :laboratorio_id, style: "display: block" , class: "form-label"%>
      <%= form.collection_select :laboratorio_id, Laboratorio.order(:sigla).all, :id, :sigla, {:include_blank => "" }, {class: "form-select"} %>
    </div>
  </div>

  <div>
    <%= form.submit "Salvar", class: "btn btn-dark mt-3" %>
    <%= link_to "Voltar", professors_path, class: "btn btn-dark mt-3" %>
  </div>

<% end %>

app/views/professors/_professor.html.erb
<div id="<%= dom_id professor %>">

  <h4>Dados do Professor</h4>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <p>
        <strong>Matricula:</strong>&nbsp;<%= professor.matricula %>&nbsp;&nbsp;&nbsp;&nbsp;
        <strong>Nome:</strong>&nbsp;<%= professor.nome %>
        </p>
        <p>
        <strong>Cpf:</strong>&nbsp;<%= professor.cpf %>&nbsp;&nbsp;&nbsp;&nbsp;
        <strong>Tipo professor:</strong>&nbsp;<%= professor.tipo_professor.descricao %>
        </p>
        <strong>Laboratorio:</strong>&nbsp;<%= professor.laboratorio.nome %>

        <br/><br/>

        <% professor.projeto_professors.each do |projeto| %>
          <div class="card">
            <div class="card-header">Projeto</div>
            <div class="card-body">
              <strong>Titulo:</strong>&nbsp;<%= projeto.projeto.titulo %><br/>
              <strong>Inicio:</strong>&nbsp;<%= projeto.inicio %>&nbsp;&nbsp;&nbsp;&nbsp;
              <strong>Fim:</strong>&nbsp;<%= projeto.fim %>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>

</div>

app/views/professors/edit.html.erb
<h1>Edit professor</h1>

<%= render "form", professor: @professor %>

<br>

app/views/professors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Professor</h1>

<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Consultar
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">

        <%= form_with url: professors_path, method: :get do %>
          <%= label_tag :nome, 'Nome:' , {class: "form-label"} %>
          <%= text_field_tag :nome ,{}, {class: "form-control col-sm-10"} %>
          <%= submit_tag 'Pesquisar', {class: "btn btn-dark mt-3"} %>
        <% end %>

      </div>
    </div>
  </div>
</div>

<br/>

<%= link_to "Novo", new_professor_path, class: "btn btn-dark mt-3" %>

<br/><br/>

<form>
  <table class="table table-striped table-bordered table-hover mt-4">
    <tbody>
      <% if !@professors.nil? %>
        <%= paginate @professors, theme: 'bootstrap-5'%>
        <% @professors.each do |professor| %>
          <tr class="align-middle">
            <td class="col-lg-4" ><%= link_to professor.nome, professor_path(professor) %></td>
            <td class="col-sm-1" ><%= link_to "Editar", edit_professor_path(professor), class: "btn btn-dark btn-sm" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</form>

app/views/professors/new.html.erb
<h1>Professor</h1>

<%= render "form", professor: @professor %>

<br>

app/views/professors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @professor %>

<div>
  <%= link_to "Editar", edit_professor_path(@professor), class: "btn btn-dark mt-3" %>
  <%= link_to "Voltar", professors_path, class: "btn btn-dark mt-3" %>
</div>