config/routes.rb
Rails.application.routes.draw do
  resources :documento_alunos
  resources :tipo_documentos
  resources :projeto_alunos
  resources :projeto_professors
  resources :tipo_bolsas
  resources :alunos
  resources :cotas
  resources :projetos
  resources :area_conhecimentos
  resources :professors
  resources :cursos
  resources :instituicaos
  resources :laboratorios
  resources :centros
  resources :tipo_professors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "application#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :curso
  belongs_to :cota

  has_many :documento_alunos
  accepts_nested_attributes_for :documento_alunos, reject_if: :all_blank, allow_destroy: true

  has_many :projeto_alunos
  has_many :projetos, through: :projeto_alunos
  accepts_nested_attributes_for :projetos


end

app/models/area_conhecimento.rb
class AreaConhecimento < ApplicationRecord
end

app/models/centro.rb
class Centro < ApplicationRecord
  validates  :nome, :sigla, :presence => { :message => " é um campo obrigatório !"}
end

app/models/cota.rb
class Cota < ApplicationRecord
  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
end

app/models/curso.rb
class Curso < ApplicationRecord
  belongs_to :centro
  belongs_to :instituicao

  validates  :nome, :sigla, :presence => { :message => " é um campo obrigatório !"}
end

app/models/documento_aluno.rb
class DocumentoAluno < ApplicationRecord
  belongs_to :aluno
  belongs_to :tipo_documento

  has_one_attached :documento
end

app/models/instituicao.rb
class Instituicao < ApplicationRecord
  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
end

app/models/laboratorio.rb
class Laboratorio < ApplicationRecord
  belongs_to :centro

  #validates_associated :centro, :message => " O centro deve existir !"

  validates  :nome, :presence => { :message => " é um campo obrigatório !"}
  validates  :sigla, :presence => { :message => " é um campo obrigatório !"}
  validates  :centro, :presence => { :message => " é um campo obrigatório !"}
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :tipo_professor
  belongs_to :laboratorio

  has_many :projeto_professors
  has_many :projetos, through: :projeto_professors
  accepts_nested_attributes_for :projetos
end

app/models/projeto.rb
class Projeto < ApplicationRecord
  belongs_to :area_conhecimento

  has_many :projeto_professors
  has_many :projeto_alunos

  accepts_nested_attributes_for :projeto_alunos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :projeto_professors, reject_if: :all_blank, allow_destroy: true

  has_many :alunos, through: :projeto_alunos
  accepts_nested_attributes_for :alunos

  has_many :professors, through: :projeto_professors
  accepts_nested_attributes_for :professors
end

app/models/projeto_aluno.rb
class ProjetoAluno < ApplicationRecord
  belongs_to :projeto
  belongs_to :aluno
  belongs_to :tipo_bolsa
end

app/models/projeto_professor.rb
class ProjetoProfessor < ApplicationRecord
  belongs_to :projeto
  belongs_to :professor

  
end

app/models/tipo_bolsa.rb
class TipoBolsa < ApplicationRecord

  validates  :nome, :valor, :presence => { :message => " é um campo obrigatório !"}

end

app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord
end

app/models/tipo_professor.rb
class TipoProfessor < ApplicationRecord

  validates  :descricao, :presence => { :message => "é um campo obrigatório !"}

end

app/controllers/area_conhecimentos_controller.rb
class AreaConhecimentosController < ApplicationController
  before_action :set_area_conhecimento, only: %i[ show edit update destroy ]

  # GET /area_conhecimentos or /area_conhecimentos.json
  def index
    @area_conhecimentos = AreaConhecimento.all
  end

  # GET /area_conhecimentos/1 or /area_conhecimentos/1.json
  def show
  end

  # GET /area_conhecimentos/new
  def new
    @area_conhecimento = AreaConhecimento.new
  end

  # GET /area_conhecimentos/1/edit
  def edit
  end

  # POST /area_conhecimentos or /area_conhecimentos.json
  def create
    @area_conhecimento = AreaConhecimento.new(area_conhecimento_params)

    respond_to do |format|
      if @area_conhecimento.save
        format.html { redirect_to @area_conhecimento, notice: "Area conhecimento was successfully created." }
        format.json { render :show, status: :created, location: @area_conhecimento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @area_conhecimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /area_conhecimentos/1 or /area_conhecimentos/1.json
  def update
    respond_to do |format|
      if @area_conhecimento.update(area_conhecimento_params)
        format.html { redirect_to @area_conhecimento, notice: "Area conhecimento was successfully updated." }
        format.json { render :show, status: :ok, location: @area_conhecimento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @area_conhecimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /area_conhecimentos/1 or /area_conhecimentos/1.json
  def destroy
    @area_conhecimento.destroy!

    respond_to do |format|
      format.html { redirect_to area_conhecimentos_path, status: :see_other, notice: "Area conhecimento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area_conhecimento
      @area_conhecimento = AreaConhecimento.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def area_conhecimento_params
      params.expect(area_conhecimento: [ :descricao ])
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/area_conhecimentos_helper.rb
module AreaConhecimentosHelper
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/helpers/cotas_helper.rb
module CotasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/area_conhecimentos/_area_conhecimento.html.erb
<div id="<%= dom_id area_conhecimento %>">
  <p>
    <strong>Descricao:</strong>
    <%= area_conhecimento.descricao %>
  </p>

</div>

app/views/area_conhecimentos/_form.html.erb
<%= form_with(model: area_conhecimento) do |form| %>
  <% if area_conhecimento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(area_conhecimento.errors.count, "error") %> prohibited this area_conhecimento from being saved:</h2>

      <ul>
        <% area_conhecimento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/area_conhecimentos/edit.html.erb
<% content_for :title, "Editing area conhecimento" %>

<h1>Editing area conhecimento</h1>

<%= render "form", area_conhecimento: @area_conhecimento %>

<br>

<div>
  <%= link_to "Show this area conhecimento", @area_conhecimento %> |
  <%= link_to "Back to area conhecimentos", area_conhecimentos_path %>
</div>

app/views/area_conhecimentos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Area conhecimentos" %>

<h1>Area conhecimentos</h1>

<div id="area_conhecimentos">
  <% @area_conhecimentos.each do |area_conhecimento| %>
    <%= render area_conhecimento %>
    <p>
      <%= link_to "Show this area conhecimento", area_conhecimento %>
    </p>
  <% end %>
</div>

<%= link_to "New area conhecimento", new_area_conhecimento_path %>

app/views/area_conhecimentos/new.html.erb
<% content_for :title, "New area conhecimento" %>

<h1>New area conhecimento</h1>

<%= render "form", area_conhecimento: @area_conhecimento %>

<br>

<div>
  <%= link_to "Back to area conhecimentos", area_conhecimentos_path %>
</div>

app/views/area_conhecimentos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @area_conhecimento %>

<div>
  <%= link_to "Edit this area conhecimento", edit_area_conhecimento_path(@area_conhecimento) %> |
  <%= link_to "Back to area conhecimentos", area_conhecimentos_path %>

  <%= button_to "Destroy this area conhecimento", @area_conhecimento, method: :delete %>
</div>